name: legacy_ci

on:
  push:
    branches:
      - 'main'

env:
  REGISTRY: ghcr.io

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Checkout Code
        uses: actions/checkout@v3
      - name: Build docker images
        run: |
          docker build . -t henryscheible/plmbias:latest -t ghcr.io/henryscheible/plmbias:latest -t ghcr.io/henryscheible/plmbias:${{  github.sha  }}
          docker build ./experiments/train -t henryscheible/train:latest -t ghcr.io/henryscheible/train:latest -t ghcr.io/henryscheible/train:${{  github.sha  }}
          docker build ./experiments/shapley -t henryscheible/shapley:latest -t ghcr.io/henryscheible/shapley:latest -t ghcr.io/henryscheible/shapley:${{  github.sha  }}
          docker build ./experiments/ablation -t henryscheible/ablation:latest -t ghcr.io/henryscheible/ablation:latest -t ghcr.io/henryscheible/ablation:${{  github.sha  }}
          docker build ./experiments/ss_ablation -t henryscheible/ss_ablation:latest -t ghcr.io/henryscheible/ss_ablation:latest -t ghcr.io/henryscheible/ss_ablation:${{  github.sha  }}
          docker push -a ghcr.io/henryscheible/plmbias

          docker run -e IS_TEST=true -e WANDB_API_KEY=${{ secrets.WANDB_TOKEN }} --rm henryscheible/train:latest
          docker push -a ghcr.io/henryscheible/train

          docker run -e IS_TEST=true -e WANDB_API_KEY=${{ secrets.WANDB_TOKEN }} --rm henryscheible/shapley:latest
          docker push -a ghcr.io/henryscheible/shapley

          docker run -e IS_TEST=true -e WANDB_API_KEY=${{ secrets.WANDB_TOKEN }} --rm henryscheible/ablation:latest
          docker push -a ghcr.io/henryscheible/ablation
          docker push -a ghcr.io/henryscheible/ss_ablation