name: ghcr_ci

on:
  workflow_run:
    workflows: ["build_base_image"]
    branches: [main]
    types:
      - completed

env:
  REGISTRY: ghcr.io
  TEST_TAG: train:test
  PUSH_TAGS: ghcr.io/henryscheible/train:latest, ghcr.io/henryscheible/train:${{  github.sha  }}

jobs:
  docker:
    if: ${{  github.event.workflow_run.conclusion == 'success'  }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Checkout Code
        uses: actions/checkout@v3
      - name: Build and export
        uses: docker/build-push-action@v4
        with:
          context: ./experiments/train
          load: true
          tags: ${{  env.TEST_TAG  }}
      - name: Test
        run: | 
          docker run -e IS_TEST=true -e WANDB_API_KEY=${{ secrets.WANDB_TOKEN }} --rm henryscheible/train:latest
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./experiments/train
          push: true
          tags: ${{  env.PUSH_TAGS  }}